# Generated by Django 4.1 on 2022-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=132)),
                ('posicao', models.CharField(max_length=100)),
                ('img_url', models.CharField(default='https://pbs.twimg.com/profile_images/1265738409810722816/cLkZUf3f_400x400.jpg', max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=132)),
                ('preco', models.FloatField(default=0.0)),
                ('ingredientes', models.CharField(max_length=300)),
                ('img_url', models.CharField(max_length=999)),
            ],
        ),
    ]
