# Generated by Django 4.1 on 2022-08-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=132)),
                ('valor', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=132)),
                ('valor', models.FloatField(default=0.0)),
                ('adc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cardapio.adicional')),
            ],
        ),
    ]
