# Generated by Django 4.1 on 2022-08-28 20:36

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=132)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Telefone Padrão', max_length=31)),
                ('dia', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
    ]
