# Generated by Django 4.1 on 2022-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='bom',
            field=models.BooleanField(default=False),
        ),
    ]
