# Generated by Django 4.0.6 on 2022-08-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0002_produto_bom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='adc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cardapio.adicional'),
        ),
    ]
