# Generated by Django 4.1 on 2022-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cardapio', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=132)),
                ('posicao', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=999)),
            ],
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
